import {IProduct} from './types/IProduct';
import product1 from './images/product1.png';
import product2 from './images/product2.png';
import product3 from './images/product3.png';
import product4 from './images/product4.png';
import product5 from './images/product5.png';
import product6 from './images/product6.png';
import product7 from './images/product7.png';
import product9 from './images/product9.png';
import product8 from './images/product8.png';
import product10 from './images/mostPopularA.png';


export const products: IProduct[] = [
  {
    id: 1,
    image: product1,
    name: 'product 1',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
    triangle: 'new',
  },
  {
    id: 2,
    image: product2,
    name: 'product 2',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
    triangle: 'sale',
  },
  {
    id: 3,
    image: product3,
    name: 'product 3',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
  {
    id: 4,
    image: product4,
    name: 'product 4',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
  {
    id: 5,
    image: product5,
    name: 'product 5',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
  {
    id: 6,
    image: product6,
    name: 'product 6',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
    triangle: 'sale',
  },
  {
    id: 7,
    image: product7,
    name: 'product 7',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
  {
    id: 8,
    image: product8,
    name: 'product 8',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
  {
    id: 9,
    image: product9,
    name: 'product 9',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
  {
    id: 10,
    image: product10,
    name: 'product 10',
    price: 1875,
    color: 'pink',
    size: 's',
    quantity: 1,
    smallDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum.',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer et nisi erat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. Nunc eu commodo tellus. Mauris faucibus leo quis urna porta, at rutrum massa efficitur. Donec tempor bibendum ex, sit amet lacinia nibh ultrices sit amet.',
    additionalInfo: 'Duis a ex id turpis consectetur consequat et in libero. Integer varius consequat pulvinar. Quisque at mattis diam.',
    tags: ['Dress', 'Striped', 'Detailed Swing Dress'],
    reviews: [
      {
        title: 'Must have!',
        rating: 5,
        text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
        date: '25.04.2022',
        author: 'Liya Andrade',
      },
      {
        title: 'Very good',
        rating: 4,
        text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
        date: '29.04.2022',
        author: 'Anisa Bell',
      },
    ],
  },
];
