import {IProductReviews} from './types/IProductReviews';

export const productReviews: IProductReviews = {
  product1: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product2: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product3: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product4: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Product4 is very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product5: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product6: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product7: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product8: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product9: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
  product10: [
    {
      id: 1,
      title: 'Must have!',
      rating: 5,
      text: 'Maximus nisl lorem, a pulvinar arcu mattis vitae. Vivamus porta, nisi ut tempor viverra, sed lacinia mauris sapien in lorem. Fusce posuere semper eros nec porttitor. Proin odio justo, maximus sed eros nec, luctus convallis ligula.',
      date: '25.04.2022',
      author: 'Liya Andrade',
    },
    {
      id: 2,
      title: 'Very good',
      rating: 4,
      text: 'In sed tortor at sapien accumsan congue. Phasellus aliquet, justo eu varius egestas, ex lectus mattis nulla. Vivamus rhoncus ante turpis, nec dictum nulla convallis vitae.',
      date: '29.04.2022',
      author: 'Anisa Bell',
    },
  ],
};
